### ISSUE TITLE
Gulp Error: write EPIPE throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by admonkey** [kenarkose/Files#3]
gulp won't execute, but tests work fine when run manually and on travis-ci

```
(node:29747) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[21:56:42] Using gulpfile /var/www/Files/Gulpfile.js
[21:56:42] Starting 'test'...
[21:56:42] Finished 'test' after 20 ms
[21:56:42] Starting 'watch'...
[21:56:42] Finished 'watch' after 35 ms
[21:56:42] Starting 'default'...
[21:56:42] Finished 'default' after 41 μs
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1012:11)
    at WriteWrap.afterWrite (net.js:793:14)
```

gulp version 3.9.1
node v6.3.1
npm 3.10.3
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
linux ubuntu 14.04 desktop

**Comment by admonkey** [comment]
Thoughts:: I also noticed that the `composer.lock` file isn't in version control - may have some configuration drift issues over time. I'm not sure what the npm equivalent is to that, but I have a suspicion it might have been helpful in this situation. On that tangent, adding `composer.lock` and changing the test path to `vendor/bin/phpunit` instead of system dependency `phpunit` might be helpful too when versioning spreads out between systems. Lastly, maybe gulp watch the actual source files for changes instead of just the tests themselves.

**Comment by Hyleeh** [comment]
I recently removed `composer.lock` from version control (in almost all my packages) due to a Travis integration problem which was not really easy to fix (at least with my knowledge of travis)
Travis loads composer.lock dependencies and package dependencies are not resolved in every version regarding PHP, Laravel and orchestra/testbence since some dependencies require different versions

In that case, any ideas on how to run continuous integration with the lock while on different versions of dependencies and PHP?

Feel free to open more pull requests and issues
(BTW, Added source files to gulp watch)

**Comment by admonkey** [comment]
That's an interesting problem I haven't encountered yet. I was wondering why you added orchestra/testbench in the travis script itself. I'll keep an eye out for a solution.

**Comment by Hyleeh** [comment]
Testbench provides a really easy way to test laravel specific functionality
This didn't use to be like this until recently when travis ignored composer.lock
